[package]
name = "obsidian-tidy"
version = "0.1.0"
edition = "2024"
authors = ["CryptoGladi <dam.almaev@gmail.com>"]
description = "Blazingly fast Obsidian vault linter"
repository = "https://github.com/CryptoGladi/obsidian-tidy"
documentation = "https://docs.rs/obsidian-tidy/latest/obsidian_tidy"
license = "GPL-3.0-or-later"
keywords = ["obsidian", "vault", "linter", "tidy", "knowledge-graph", "graph"]
categories = ["parser-implementations", "data-structures"]

[profile.bench]
debug = true

[workspace]
members = [
  "obsidian-tidy-core",
  "obsidian-tidy-rules",
  "obsidian-tidy-logger",
  "obsidian-tidy-cli",
  "obsidian-tidy-config",
  "obsidian-tidy-macros",
  "obsidian-tidy-parser", "obsidian-tidy-parser-wasm",
]

[workspace.dependencies]
obsidian-tidy-logger = { path = "./obsidian-tidy-logger" }
obsidian-tidy-core = { path = "./obsidian-tidy-core" }
obsidian-tidy-rules = { path = "./obsidian-tidy-rules" }
obsidian-tidy-config = { path = "./obsidian-tidy-config" }
obsidian-tidy-cli = { path = "./obsidian-tidy-cli" }
obsidian-tidy-macros = { path = "./obsidian-tidy-macros" }
obsidian-tidy-parser = { path = "./obsidian-tidy-parser" }
tokio = { version = "1.52", features = ["macros", "rt-multi-thread"] }
futures = "0.3"
tracing = "0.1"
obsidian-parser = { version = "0.9", features = ["petgraph", "rayon"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
serde_json = "1.0"
tracing-test = "0.2"
itertools = "0.14"
clap = { version = "4.5", features = ["env", "derive", "unicode", "string"] }
rayon = "1.11"
tracing-subscriber = { version = "0.3", features = ["env-filter", "ansi"] }
erased-serde = "0.4.10"
proptest = "1.11.0"
tempfile = "3.25"
strum = { version = "0.28", features = ["derive"] }
derive_more = { version = "2", features = ["is_variant"] }
miette = { version = "7.6", features = ["fancy", "syntect-highlighter"] }
serial_test = "3.4"
gag = "1"
insta = { version = "1.47", features = ["json"] }
criterion = { version = "0.8", features = ["html_reports"] }
static_assertions = "1.1"
dhat = "0.3"
inventory = "0.3"
gungraun = "0.19"
pastey = "0.2"
ouroboros = "0.18"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
private_intra_doc_links = "allow"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
panic = "warn"
expect_used = "warn"
missing_errors_doc = "allow"
undocumented_unsafe_blocks = "warn"
needless_pass_by_value = "warn"
missing_const_for_fn = "warn"
or_fun_call = "warn"

[lints]
workspace = true

[dependencies]
obsidian-tidy-logger.workspace = true
obsidian-tidy-core.workspace = true
obsidian-tidy-cli.workspace = true
tracing.workspace = true
serde.workspace = true
thiserror.workspace = true
miette.workspace = true
