[package]
name = "obsidian-tidy-lexer"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[features]
default = ["tracing"]
tracing = ["dep:tracing"]

[dependencies]
# TODO ADD  cargo build -p obsidian-tidy-parser --target thumbv7m-none-eabi -Zbuild-std=core,alloc
# For check 
# Not found no_std mode
pulldown-cmark = { git = "https://github.com/pulldown-cmark/pulldown-cmark", rev = "41bca7b3daf86358c32b6dc46aba50c926be5c8d", default-features = false, features = [
    "hashbrown",
] }
serde = { workspace = true, features = ["derive", "alloc"] }
derive_more = { workspace = true, features = ["is_variant"] }
strum = { workspace = true, features = ["derive"] }
tracing = { workspace = true, optional = true }
static_assertions.workspace = true
pastey.workspace = true

[dev-dependencies]
insta.workspace = true
serde_json = { workspace = true, features = ["std"] }
proptest.workspace = true
tracing-test.workspace = true

[lints]
workspace = true
