[package]
name = "obsidian-tidy-config"
version = "0.0.0"
edition = "2024"
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
obsidian-tidy-core.workspace = true
obsidian-tidy-rules.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde.workspace = true
clap.workspace = true
serde_json.workspace = true
strum.workspace = true
derive_more.workspace = true

[dev-dependencies]
tracing-test.workspace = true
insta.workspace = true
