[package]
name = "obsidian-tidy-core"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
directories = "6.0"
obsidian-parser.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
erased-serde.workspace = true

[dev-dependencies]
tracing-test.workspace = true
serde_json.workspace = true
