[package]
name = "obsidian-tidy-core"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
directories = "6.0"
obsidian-parser.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
erased-serde.workspace = true
strum.workspace = true
derive_more.workspace = true
serde_json.workspace = true        # TODO Add features for test and bench
static_assertions.workspace = true
inventory.workspace = true

[dev-dependencies]
tracing-test.workspace = true
insta.workspace = true
criterion.workspace = true
dhat.workspace = true
serial_test.workspace = true

[target.'cfg(target_os = "linux")'.dev-dependencies]
gungraun.workspace = true

[[bench]]
name = "criterion-deserialization"
harness = false

[[bench]]
name = "gungraun-deserialization"
harness = false

[[bench]]
name = "memory-profile-deserialization"
harness = false
