[package]
name = "obsidian-tidy-core"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
directories = "6.0"
obsidian-parser.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
erased-serde.workspace = true
strum.workspace = true
derive_more.workspace = true
serde_json.workspace = true        # TODO Add features for test and bench
dhat.workspace = true
static_assertions.workspace = true

[dev-dependencies]
tracing-test.workspace = true
insta.workspace = true
criterion.workspace = true

[[bench]]
name = "deserialization"
harness = false

[[bench]]
name = "memory_profile_deserialization"
harness = false
